# @generated by generate_proto_mypy_stubs.py.  Do not edit!
from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)


class Embedding(google___protobuf___message___Message):
    embedding_vector = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[float]

    def __init__(self,
        embedding_vector : typing___Optional[typing___Iterable[float]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Embedding: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class PhraseEmbeddingNgram(google___protobuf___message___Message):
    ngram = ... # type: typing___Text
    attention = ... # type: float

    def __init__(self,
        ngram : typing___Text,
        attention : typing___Optional[float] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> PhraseEmbeddingNgram: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class PhraseEmbedding(google___protobuf___message___Message):
    phrase = ... # type: typing___Text
    count = ... # type: int

    @property
    def embedding(self) -> Embedding: ...

    @property
    def ngrams(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[PhraseEmbeddingNgram]: ...

    def __init__(self,
        embedding : Embedding,
        phrase : typing___Text,
        count : int,
        ngrams : typing___Optional[typing___Iterable[PhraseEmbeddingNgram]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> PhraseEmbedding: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
